name: 'Coverage Setup'

outputs:
    COVERAGE_PROCESS_START:
        description: ".coveragerc file location. Needs to be set for coverage to run"
        value: ${{steps.covrc-dir-report.outputs.COVERAGE_PROCESS_START }}

runs:
  using: "composite"
  steps:
    - name: Installation
      run: |
        python -m pip install coverage
      shell: bash
    - name: Directory Creation
      run: |
        INSTALL_DIR=$(cd tests; python -c "import pyccel; print(pyccel.__path__[0])")
        SITE_DIR=$(python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')
        echo "SITE_DIR = ${SITE_DIR}"
        echo -e "import coverage; coverage.process_startup(); print('starting')" > ${SITE_DIR}/pyccel_cov.pth
        cat ${SITE_DIR}/pyccel_cov.pth
        echo -e "[run]\nparallel = True\nsource = ${INSTALL_DIR}\ndata_file = $(pwd)/.coverage\n[report]\ninclude = ${INSTALL_DIR}/*\n[xml]\noutput = cobertura.xml" > .coveragerc
      shell: bash
    - name: Coveragerc directory definition
      id: covrc-dir-report
      run: echo "::set-output name=COVERAGE_PROCESS_START::$(pwd)/.coveragerc"
      shell: bash
