name: 'Coverage Collection'

runs:
  using: "composite"
  steps:
    - name: Coverage collection
      run: |
        cd tests
        coverage combine
        coverage xml
        rm ${SITE_DIR}/pyccel_cov.pth
        cd ..
      shell: bash

